#
# =============================================================================
# Chirpy - A minimal, responsive, and feature-rich Jekyll theme.
# © 2019 Cotes Chung
# MIT License
# =============================================================================

# Site settings
title: Centro de Cálculo 
tagline: Escuela Superior de Ingeniería y Tecnología
description: >-
  Servicios, recursos, guías y artículos.
url: 'https://universidad-de-la-laguna.github.io'
baseurl: '/esit-cc-web'
lang: es
author: Centro de Cálculo ESIT

# Theme
theme: jekyll-theme-chirpy

# Plugins
plugins:
  
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# Collections
collections:
  tabs:
    output: true
    sort_by: order
  posts:
    output: true
    permalink: /posts/:title/

# Tabs
tabs:
  # Disable the default Home tab
  home: true

# Defaults
defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: ''
      type: tabs
    values:
      layout: page
      permalink: /:title/

# Pagination
paginate: 5 # Number of posts per page
paginate_path: /posts/page:num/

# SEO
twitter:
  username: ULL

# Avatar
avatar: '/assets/img/marca-ull-circulo.svg' # Logo de la ULL

# Social
social:
  name: Centro de Cálculo
  email: ccalculo.esit@ull.edu.es
  links:
    - https://twitter.com/ULL
    - https://github.com/Universidad-de-la-Laguna

# Comments (opcional, puedes configurar Disqus)
# disqus:
#   shortname: # tu-shortname-de-disqus

# Analytics (opcional)
# google_analytics: # tu-id-de-google-analytics
