title: "Centro de Cálculo ESIT"
description: "Knowledge Base para estudiantes de IT"
url: "https://universidad-de-la-laguna.github.io"
baseurl: "/esit-cc-web"

# Tema moderno - elige uno:
remote_theme: pages-themes/cayman@v0.2.0        # Limpio y profesional
# remote_theme: pages-themes/architect@v0.2.0    # Más técnico
# remote_theme: pages-themes/slate@v0.2.0        # Oscuro y elegante

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

# Colores personalizados (para tema Cayman)
cayman:
  project_name: "Knowledge Base IT"
  project_tagline: "Recursos y guías del Centro de Cálculo"

# SEO
lang: es
author: "Centro de Cálculo ESIT"