title: ESIT - Centro de Cálculo
description: >-
  Servicios, recursos, guías y artículos del Centro de Cálculo de la Escuela Superior de Ingeniería y Tecnología de la Universidad de La Laguna.
author: Centro de Cálculo ESIT

theme: jekyll-theme-minimal

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"